### PR TITLE
Restructured project to MVC architecture

### PR DESCRIPTION
**Pull request by yatendra2001**
Restructured again with null safety.
Sorry for inconvenience, i forked repository when it didn't have null safety.

### CODE REVIEW

**Comment by Harishwarrior** [comment]
There is some conflicts again in upload_profile,dart. Please merge those changes.

**Comment by Harishwarrior** [comment]
> You may check now, I have resolved them an import was wrong

Conflicting files
lib/admin/screens/upload_profile.dart

kindly please check again

**Comment by yatendra2001** [comment]
did you mean lib/views/admin/screens/upload_profile.dart ?

**Comment by Harishwarrior** [comment]
> did you mean lib/views/admin/screens/upload_profile.dart ?

image

**Comment by yatendra2001** [comment]
is it fine now ?

**Comment by Harishwarrior** [comment]
> is it fine now ?

Still conflicting.
Try this.
Step 1: From your project repository, check out a new branch and test the changes.

git checkout -b yatendra2001-master master
git pull https://github.com/yatendra2001/student_app.git master
Step 2: Merge the changes and update on GitHub.

git checkout master
git merge --no-ff yatendra2001-master
git push origin master
@Harishwarrior

**Comment by yatendra2001** [comment]
I don't understand, it's still now working, I will create a new fork and again convert it to MVC and create a new pull request.

**Comment by yatendra2001** [comment]
@Harishwarrior I have created a new pull request that do not have any branch conflicts you may check it.

**Comment by Harishwarrior** [comment]
#22 Closed

**Pull request closed without merging**
